### ISSUE TITLE
Map not updating w/new deads

### ISSUE THREAD

**Issue by phreekbird** [Garrett92/WurmMapGen#10]
Ran the command:  `java -Xmx128M -jar -Djava.awt.headless=true WurmMapGen.jar -v`
Log found here: https://pastebin.com/ePLZEadi

So the map works and displays but i have had two new villages created, nothing new has shown up. Also built all kinds of roads and that's not showing up either. 
I have restarted apache2, restarted the entire server, restarted wurm, but nothing is "forcing" an update on the map. http://play.phreekbird.net/

**Comment by woubuc** [comment]
When you run the application, it generates the map images based on the server data at that time. To update the images, you'll need to run the generator again.

**Comment by phreekbird** [comment]
yea i have a cron job running every 15 mins, i even ran the app manually and the web site still isn't updating. I think i'm going to ditch apache2 and try nginx see if that helps.
