### ISSUE TITLE
WurmMapGen.jar does not start

### ISSUE THREAD

**Issue by Murgen75** [Garrett92/WurmMapGen#13]
Hello! I did everything as written in the step-by-step guide to step 3, there i got an error. Maybe i did something wrong, and you will see what my mistake is? Sorry for my English, this is all Google translator.
![Desktop Screenshot 2020 08 30 - 12 58 10 92](https://user-images.githubusercontent.com/70458598/91650320-52fb2580-eac1-11ea-9967-29ae8f6b8f46.png)

**Comment by Murgen75** [comment]
I solved this problem. Did it as you did, put WurmMapGen on the C drive, and everything started. But now i have another problem, Apache won't start.
![Desktop Screenshot 2020 09 01 - 11 53 18 42](https://user-images.githubusercontent.com/70458598/91786141-4950f980-ec4a-11ea-8098-8510f45a1811.png)
And that was where it stopped.

**Comment by woubuc** [comment]
I'm glad you were able to solve your issue. It probably had to do with how Windows and/or Java handles drive letters, which explains why it worked when you put them on the same drive.

Apache not starting does not sound like a problem with the map generator either, so I'm going to go ahead and close this issue. I think there are other places that will be able to better help you with that, as I know next to nothing about Apache or Xampp.
